import Head from "next/head";
import Board from "../../components/Board/Board";
import Button from "../../components/Button";
import useNewBoardActions from "../../hooks/useNewBoardActions";
import useAtomSubscribers from "../../state/useAtomSubscribers";

export default function Room() {
  useAtomSubscribers();

  const { generateNewBoard } = useNewBoardActions();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Board />
      <Button onClick={generateNewBoard}>Generate New Board</Button>
    </>
  );
}
