import Head from "next/head";
import Button from "../components/Button";
import useNewRoomActions from "../hooks/useNewRoomActions";

export default function Home() {
  const { navigateToNewRoom } = useNewRoomActions();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button onClick={navigateToNewRoom}>Generate New Room</Button>
    </>
  );
}
